Repository CharsetDetector/UTF-unknown, pull requests merged in 2019-11, with the labels that each got.

#81 Fix codepage name 'mac-centraleurope' to 'x-mac-ce'
  src/Core/CodepageName.cs
  tests/Data/x-mac-ce/lang_cs_mac-centraleurope.txt
Labels: bug

#84 Resolve todo by TIS_620 equal iso-8859-11 with comment
  src/Core/CodepageName.cs
Labels: documentation, enhancement

#87 Fix todo commits by fixing the docs
  src/Core/CodepageName.cs
Labels: documentation

#86 Resolve todo fix cp949 to ks_c_5601-1987
  src/Core/CodepageName.cs
  src/Core/Probers/MultiByte/Korean/CP949Prober.cs
  src/DetectionDetail.cs
Labels: enhancement

#88 Add support 2-byte arrays for utf with bom
  src/CharsetDetector.cs
  tests/CharsetDetectorTest.cs
Labels: feature

#89 fix typo
  tests/CharsetDetectorTest.cs
Labels: refactor

#90 Improve link comment
  src/DetectionDetail.cs
Labels: documentation

#91 Fix XML docs warnings
  src/Core/Models/StateMachineModel.cs
Labels: documentation

#92 Small Cleanup and refactor
  UTF-unknown.sln.DotSettings
  src/CharsetDetector.cs
  src/Core/Analyzers/MultiByte/Japanese/EUCJPDistributionAnalyser.cs
  src/DetectionDetail.cs
  src/DetectionResult.cs
Labels: refactor

#93 remove old example
  src/CharsetDetector.cs
Labels: documentation

#94 Support snupkg
  appveyor.yml
  src/UTF-unknown.csproj
Labels: feature

#96 Added Rustam Sayfutdinov as author to package
  src/UTF-unknown.csproj
Labels: documentation

#97 Fix todo: ISO-2022-CN is x-cp50227 in .NET
  src/Core/CodepageName.cs
  src/DetectionDetail.cs
Labels: enhancement
