Repository CharsetDetector/UTF-unknown, pull requests merged in 2019-10, with the labels that each got.

#68 Support .NET Core 2 and .NET Standard 2
  src/CharsetDetector.cs
  src/UTF-unknown.csproj
  tests/CharsetDetectorTestBatch.cs
  tests/EncodingJsonConverter.cs
  tests/UTF-unknown.Tests.csproj
Labels: feature

#69 Version 2.2
  appveyor.yml
  src/UTF-unknown.csproj
Labels: release

#71 Fix typo in `streams`
  README.md
  src/UTF-unknown.csproj
Labels: documentation
